### ISSUE TITLE
Support Capybara >= 3.37

### ISSUE THREAD

**Issue by wintersolutions** [phillbaker/capybara-mechanize#73]
Commit https://github.com/phillbaker/capybara-mechanize/commit/3341388eee5762222407d9602af6b96d6960ff45 restricted Capybara versions to <= 3.36. Capybara has released 3.38 already and the Gems will get more out of sync as time progresses.

Breaking change in Capybara:

https://github.com/teamcapybara/capybara/commit/ec5a50f93318a1d080347f88e5d8dbfc072f1862

**Comment by phillbaker** [comment]
fixed in https://github.com/phillbaker/capybara-mechanize/pull/74 and released in 1.13.0

**Comment by wintersolutions** [comment]
Thank you very much for your hard work and dedication! It runs great for me...
